version: "3.8"
services:
    mysql:
      image: mysql:8.0.27
      ports:
        - 3306:3306
      restart: unless-stopped
      environment:
        # The user, password and database that Keycloak
        # is going to create and use
        MYSQL_USER: keycloak_user
        MYSQL_PASSWORD: keycloak_password
        MYSQL_DATABASE: keycloak_db
        # Self-Explanatory
        MYSQL_ROOT_PASSWORD: root_password
      volumes:
        - keycloak-and-mysql-volume:/var/lib/mysql
      networks:
        - keycloak-and-mysql-network

    keycloak:
      build:
        context: ./keycloak
      ports:
        - 8080:8080
      restart: unless-stopped
      environment:
        # User and password for the Administration Console
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        DB_VENDOR: mysql
        DB_ADDR: mysql
        DB_PORT: 3306
        # Same values as the mysql service
        DB_USER: keycloak_user
        DB_PASSWORD: keycloak_password
        DB_DATABASE: keycloak_db
        KEYCLOAK_IMPORT: /tmp/realm-keycloak-angular-sandbox.json
      depends_on:
        - mysql
      networks:
        - keycloak-and-mysql-network
      volumes:
        - ./keycloak/config/realm-keycloak-angular-sandbox.json:/tmp/realm-keycloak-angular-sandbox.json

    angular:
      restart: unless-stopped
      build:
          context: ./angular
      ports:
        - "3000:3000"
      depends_on:
        - keycloak
      networks:
        - keycloak-and-mysql-network
        
    nginx:
      restart: unless-stopped
      build:
        context: ./nginx
      ports:
        - "80:80"
      depends_on:
        - angular
      networks:
        - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
